---
title: "Discussion"
author: "Elhami A.A. Ahmed"
date: "2024"
format: 
  html:
    toc: true
    toc-location: left
    number-sections: true
    code-fold: true
execute:
  echo: false
  warning: false
  message: false
#  docx:
#    toc: true
#    number_sections: true
#    highlight-style: github
---

## Socio-economic Characteristics

We have included in our study a total of 410 participants, including 260 (61%) IDPs and 150 (39%) host community members. Taken from 6 localities, as Eldamer had the highest overall representation (30%), followed by Atbara (27%) and Shendi (17%). Then least localities with AbuHamad, Elmatama, and Barbar by (13%, 11%, & 2%) respectively.

There are obvious discrepancies in socio-demographic characteristics between the IDPs and host communities. The study population had a median age of 31 years (IQR: 25-43), with a gender distribution of 64% females and 36% males. Marital status varied, with 29% single, 56% married, and 15% divorced or widowed. Our study revealed significant socio-economic differences between IDPs and host community members. As, educational levels significantly differed, with more IDPs having university (48% vs. 40%) and post-graduate education (25% vs. 11%) (p \< .001), which could give more opportunities for the host community for development. Occupation post-conflict showed a significant shift (p \< .001), with professional employment decreasing among IDPs (from 44% to 19%) and unemployment rising (42% vs. 34%). We observed there is significant discrepancies in type of shelter among IDPs and host members (p \< .001), with IDPs more frequently lived in host communities and rented accommodations (62%) while host community members, who predominantly owned homes (82%). This even superimposed by Housing conditions, with fewer IDPs reporting good conditions (28% vs. 48%) (p \< .001). Median monthly income before the conflict was higher for IDPs (Mdn = 200) than for host community members (Mdn = 120) (p \< .001), but post-conflict income levels showed no significant difference (p = .4), this indicates the drop in earnings due to loss of employment and it appears in low income satisfaction, among both parties with no significant difference (p = .062) as shown in @fig-income-plot & @tbl-descriptive-ses . Also, we observed the displacement pattern of displaced persons from various states due to conflict, the analysis reveals that people tends to displace to the proximity safe area as evident by coming from surrounding states (**Khartoum, Aj Jazerah** and **River Nile**)

------------------------------------------------------------------------

## Social Cohesion among IDPs and Host Communities

### Social Integration and Participation of IDP Communities Towards Host Communities

The survey assessed the social integration and participation of internally displaced persons (IDPs) within the host community, focusing on friendships, acceptance, social activity engagement, experiences of kindness, comfort in seeking help, and overall social integration @tbl-descriptive-social-integration. Our study showed all of IDPs have average to high social integration into host community (100%), These findings resonate with Chuiko & Fedorenko's (2020) study, which found that the majority of IDPs exhibited medium to high levels of social integration within host communities (87.1%)[@chuiko2021].

This is supported by high friendships of IDPs from host community, majority felt accepted by the host community, with moderate social activity engagement, high experiences of kindness, and comfort in seeking help; which is emphasized by the literature that importance of factors influencing integration include friendships, feelings of acceptance, and participation in social activities [@roshchyk2024]. The findings also align with Hynie's 2018, discussion on barriers to refugee integration, pointing out that while challenges exist, active engagement and positive experiences within the host community contribute significantly to IDP integration [@hynie2018]. Tassang et al in 2023, highlighted solidarity among IDPs as crucial for promoting psychological health and community satisfaction, aspects that correlate with the high levels of acceptance and experiences of kindness reported here [@tassang2023a]. Overall, these insights underscore the multifaceted nature of social integration among IDPs, highlighting both challenges and opportunities for fostering inclusive communities.

### Shared Values & Goals Between the IDPs & Host Community

The levels of shared values and goals between host community members and internally displaced persons (IDPs), highlighting cultural alignment, mutual respect, collaboration, and shared responsibility @tbl-shared-values-desc. Overall, the shared values and goals revealed that majority of respondents had medium to high levels (78%), with a similar distribution between host community members and IDPs (p \> .9). Majority reported medium to high levels of mutual cultural values (87%), with no significant difference between host community members and IDPs (p = .4). Almost majority of respondents have mutual respect for customs and traditions in addition to their collaboration to solve community issues, with similar patterns for both groups (p = .3, .5 respectively). Although there was a trend towards more host community members (55%) always feeling shared responsibility for community improvement compared to IDPs (48%), this was not statistically significant (p = .060). This is similar to findings with Hazizova (2019) that emphasized the need to address socio-cultural needs to prevent conflicts, which resonates with the high levels of mutual respect and collaboration observed in this study [@hazizova2019]. Additionally, Duncan (2005) study found high levels of collaboration and shared responsibility [@duncan2005]. Overall, the findings suggest a strong foundation of shared values and goals between IDPs and host community members, supporting successful integration and social cohesion.

### Levels of Perceived Equity and Justice in IDPs and Host Communities

As the findings indicated a high level of consensus between IDPs and host community members regarding the need for equal access to basic services, employment opportunities, and legal protections, @tbl-social-support-desc. As evidenced by the high agreement rates and non-significant p-values (e.g., p = .5 for access to services, p = .4 for employment opportunities, and p = .2 for legal protections). However, significant differences exist in perceptions of inclusiveness in decision-making (p = .008) and experiences of discrimination (p \< .001). Specifically, 59% of IDPs found decision-making processes inclusive compared to 43% of host community members, and IDPs were less likely to perceive discrimination (41% disagreed) compared to host community members (31% disagreed). Comparatively, existing literature supports these findings by Jacobs et al. (2017) and Orach et al. (2009) emphasize the varied justice mechanisms and barriers to services faced by IDPs, indicating the need for tailored approaches to address these challenges [@orach2009; @jacobs2017]

### Level of Perceived of Social Cohesion of IDPs and Host Communities

The survey examined the perceived levels of social cohesion among host community members and internally displaced persons (IDPs), focusing on current perceptions and changes over time @tbl-perception-cohesion. Majority of respondents reported acceptable to high cohesion (60% and 28%). Interestingly, the distribution of responses did not significantly differ between host community members and IDPs (p = .6). Regarding changes over time, half of the respondents believed that social cohesion (55%) was improving. Host community members were more optimistic, with 62% reporting improvement compared to 52% of IDPs; however, were not statistically significant (p = .12). These findings align with existing research on social cohesion in forced displacement contexts as [@kuhnt2019] found similar levels of acceptable and high cohesion among displaced populations.

### Levels of Resilience Among IDPs Compared to Host Communities

Examining the levels of resilience among host community members and internally displaced persons (IDPs), focusing on psychological well-being, social support, economic resources, preparedness for environmental challenges, and overall resilience scores @tbl-resilience.

The overall resilience levels showed 62% had an average score, and 16% had a high score. IDPs were significantly more likely to have a low resilience score compared to host community members (p \< .001). Notably, IDPs tended to report lower psychological well-being compared to host community members (p \< .001), with 29% of IDPs reporting low levels versus 20% of host community members.

Regarding social resilience, both groups agreed on the social support networks as poor or acceptable (48%, 40%) (p = .7). Similarly, about economic resilience as weak or moderate (42%, 50%) (p = .4). However, IDPs were less likely to feel well-prepared for environmental challenges compared to host community members (p \< .001), with 33% of IDPs reporting poor preparedness versus 22% of host community members.

## Accessibility to Different Basic Resources

Based on our findings shedding light on the distinct challenges and support systems for internally displaced persons (IDPs) compared to host communities in conflict-affected regions @tbl-access-assoc . Healthcare services accessibility emerges as a critical issue, IDPs perceive healthcare services as less accessible than host community members. This finding aligns with previous research [@orach2013; @parwak2019], which identifies barriers such as financial constraints and inadequate availability of essential medications and trained personnel.

Similarly, education opportunities for IDPs face significant challenges, as indicated by our findings and supported by literature [@orach2013; @Ekezie2020] . Factors such as disrupted schooling, financial limitations, and geographic distance to educational facilities pose substantial barriers.

In contrast, we did not find significant differences between IDPs and host communities regarding infrastructure accessibility (roads, electricity, water supply). This contrasts with findings from other contexts [@parwak2019]**,** where conflict-induced infrastructure damage and limited maintenance impede basic service accessibility.

## Influence of Authorities and Organizations

The role of government institutions and authorities appears limited in both supporting and addressing the needs of IDPs @tbl-roles-desc, as evidenced by our study's findings and corroborated by literature [@verme2019; @orach2013]. Perceptions of minimal government involvement underscore systemic issues in governance and service delivery, necessitating policy reforms to enhance institutional support and responsiveness to displaced populations. NGO involvement also emerges as a critical factor, with our study and existing literature Ekezie et al., 2020**,** highlighting challenges in NGO service delivery due to logistical constraints and funding limitations [@Ekezie2020].

Community involvement and support mechanisms play a pivotal role in fostering resilience among IDPs and host communities alike. The findings suggest positive community engagement, echoing resilience-building strategies identified in previous studies [@horn2009]. However, variations in support from different community actors (youth, religious leaders) underscore the need for targeted engagement strategies that harness local resources and capacities.

## Associations Between Variables & Social Cohesion and Resilience

### Associations Between Various Variables and Perceived Levels of Social Cohesion

Based on our findings, several significant associations for social cohesion among internally displaced persons (IDPs) and host communities emerge @tbl-social-cohesion-assoc. These findings are crucial for understanding the dynamics that influence social cohesion in conflict-affected regions.

Older age, marriage, higher educational status are notably associated with higher perceived social cohesion, with younger individuals, single and illiterates tending to report lower cohesion levels. This resonates with the study by Hauwa ,2023, that suggests age-related differences, social networks and family structures & educational opportunities may impact social integration and community resilience efforts, highlighting a potential focus area for targeted interventions [@butu2023].

Occupation after conflict and type of shelter are also associated with social cohesion, with laborers and individuals in rented accommodations reporting lower cohesion levels. This association highlights economic stability and housing security as essential factors in shaping perceptions of community cohesion and well-being, in contrast, economic strain is negatively associated with perceptions of social cohesion in European countries [@andrews2014]**.** Also, highlighted by the study in disaster-affected communities, that factors such as housing type, injury experience, and volunteering were significantly linked to community disaster resilience and social cohesion [@ludin2018]**.**

Duration of residence in the host community significantly influences social cohesion, with longer-term residents reporting higher cohesion levels. This aligns with finding that extended periods in host communities foster familiarity, trust, and participation in social activities among IDPs [@lin2016]. This finding underscores the importance of stability and continuity in fostering trust and solidarity within communities facing displacement challenges [@butu2023]. Perceptions of discrimination based on IDP or host community status strongly influence social cohesion, with higher reported discrimination correlating with lower cohesion levels. Healthcare and education accessibility play significant roles in shaping social cohesion perceptions. Individuals who find healthcare and education easily accessible report higher cohesion levels, highlighting the critical role of accessible services in promoting community well-being and integration [@butu2023].

### Associations Between Various Variables and Social Integration & Participation

Social integration among internally displaced persons (IDPs) is influenced by a range of demographic, socio-economic, and environmental factors, as evidenced by recent studies. Age, marital status, education level, occupation, type of shelter, and duration of residence in host communities emerge as significant determinants of social integration scores @tbl-social-integ-assoc.

Older individuals, married individuals, and those with higher levels of education, such as post-graduate degrees, tend to have higher social integration scores, indicating that age, marital status, and educational attainment positively influence social integration among IDPs [@lin2016].

The locality of residence and occupation type significantly affect social integration, with Eldamer residents showing higher integration scores compared to Atbara residents, and professional employees demonstrating higher integration scores compared to laborers, indicating regional variations in community acceptance and the role of occupational status in socio-economic interactions among IDPs [@chuiko2021].

Additionally, individuals living in owned homes report higher social integration scores compared to those in rented accommodations. This association highlights the stability and socio-economic security provided by home ownership, which contributes to stronger community ties and integration [@srivarathan2022]. Longer durations of residence correlate positively with higher social integration scores, suggesting that extended periods in host communities foster familiarity, trust, and participation in social activities among IDPs [@lin2016]. In contrast, gender does not significantly correlate with social integration scores among IDPs, indicating that integration levels are not substantially influenced by gender differences Similarly, economic factors such as average monthly income before and after conflict, as well as income satisfaction for family needs, do not show significant associations with social integration scores.

### Associations Between Various Variables and Shared Values and Goals

Our analysis of factors influencing shared values among internally displaced persons (IDPs) highlights significant associations with gender, age, marital status, locality of residence, education level, occupation, displacement history, duration of residence, and attitudes towards discrimination @tbl-shared-values-assoc.

Males are more likely to report higher shared values scores compared to females (51% vs. 49%, p = 0.039). Older individuals tend to endorse higher shared values (median age 37 vs. 27 for high vs. low shared values, p \< 0.001). Married individuals align more with community values than single individuals (67% vs. 30%, p = 0.013). Eldamer residents exhibit higher shared values scores compared to Atbara residents (58% vs. 7.0%, p \< 0.001). Post-graduate individuals report higher scores compared to those with primary education (35% vs. 11%, p = 0.027). Professional employees show higher shared values compared to laborers (37% vs. 18%, p = 0.019). Those who have not experienced displacement align more with community values (8.3% vs. 51%, p \< 0.001). Longer stays in the host community are associated with higher shared values (median of 12 months for high shared values, p \< 0.001). Agreement with discriminatory practices correlates with higher shared values (60% vs. 28%, p = 0.002). Non-significant associations include displacement status, type of shelter, and various economic indicators, suggesting socio-cultural and contextual factors play a more decisive role in shaping shared community values among IDPs. These findings resonate with existing research on the social determinants of health and well-being among displaced populations. Studies from Sudan and neighboring regions highlight the intricate interplay of socio-demographic factors, displacement experiences, and community integration. For instance, studies on mental health among IDPs in Sudan reveal how factors like gender, age, and socio-economic status influence psychological well-being [@socialcohesion2018; @salah2012]. The role of education in shaping attitudes towards gender norms in conflict-affected settings further underscores the broader socio-cultural dynamics influencing community values [@scott2014].

### Associations between Different Factors and Levels of Social Support

Social support plays a crucial role in the mental health and adjustment of displaced persons as shown in @tbl-social-support-assoc. Studies have found that sociodemographic factors such as age, gender, education, income, and religiosity are associated with levels of social support among internally displaced persons (IDPs) and humanitarian migrants [@doma2022; @Ngwu2023InternallyDP]. The duration of displacement and experiences of discrimination can also impact social support levels [@Ngwu2023InternallyDP]**.** Higher levels of social support are linked to better mental health outcomes and adjustment to displacement [@chuiko2021; @doma2022] . However, displacement can lead to changes in social and cultural norms, affecting overall health [@socialcohesion2018]. Response strategies used by IDPs include a combination of health services, traditional practices, religion, and support from family and friends [@socialcohesion2018]. These findings highlight the importance of addressing social determinants of health and tailoring support programs for displaced populations.

### Associations between Different Factors and Levels of Resilience

The associations between various factors and resilience levels in the studied population reveal significant insights as detailed in @tbl-roles-resilience-assoc. Gender was not significantly associated with resilience (p = 0.3), but a trend indicated that females might exhibit slightly higher resilience, with a higher proportion of females in the high resilience group. this different from Study by Mujeeb & Zubair (2012) that highlight the heightened vulnerability of IDPs, particularly women, to lower psychological well-being and resilience in comparison to non-displaced populations [@mujeeb2012] **.** Age showed a significant association (p = 0.029), with younger individuals demonstrating higher resilience levels, highlighting developmental and contextual influences on resilience [@Daníelsdóttir2022].

Marital status was not significantly linked to resilience (p = 0.3), though married individuals were more prevalent in the high resilience group, suggesting potential social support benefits. Participant’s locality (p \< 0.001) and displacement status (p \< 0.001) were significantly associated with resilience, with IDPs showing lower resilience levels, underscoring the impact of displacement

Education level (p = 0.6) and occupation before conflict (p = 0.7) were not significantly associated with resilience. However, post-conflict occupation was significant (p = 0.009), with higher resilience linked to a higher percentage of unemployed individuals, indicating the crucial role of post-conflict economic stability. Type of shelter and housing conditions were significantly associated with resilience (p = 0.001 and p \< 0.001), linking better housing to higher resilience.

Socio-economic factors, such as monthly income before and after the conflict, were not significantly associated with resilience (p = 0.074 and p = 0.076), although higher resilience was associated with slightly higher median incomes post-conflict. Income satisfaction for family needs was significantly associated with resilience (p \< 0.001), indicating that perceived financial sufficiency is crucial for resilience.

Displacement-related factors like the number of times displaced and previous displacement were not significantly associated with resilience (p \> 0.9 and p = 0.2), nor was the duration of residence in the host community (p = 0.7). These findings suggest other factors, such as community involvement, might be more critical for resilience [@eades2013].

Access to services showed significant associations with resilience. Healthcare availability and accessibility (p \< 0.001), education opportunities (p = 0.003), and infrastructure (p \< 0.001) were linked to higher resilience, emphasizing the role of accessible services in enhancing resilience [@Okvat2011].

The roles of government institutions (p = 0.032), religious leaders (p \< 0.001), and tribal sheiks (p = 0.049) were significantly associated with higher resilience, highlighting the importance of social support networks. Support from NGOs was not statistically significant (p = 0.069), but a trend suggested higher perceived support among individuals with high resilience. Community involvement had a strong association with resilience (p \< 0.001), underlining the importance of engagement in fostering resilience [@Daníelsdóttir2022]**.** Shodeinde & Otabor (2018) emphasized the role of NGOs in facilitating integration, despite challenges in high-risk regions, which echoes the supportive social environment observed in this study [@Shodeinde2018]

## Well-Being Status of the Participants

The analysis reveals insights into the health status and well-being of IDPs compared to host community members. While physical health ratings were similar between IDPs and host community members, of fairly good level of health status. But the latter group reported significantly better social relationships and higher levels of optimism. These differences reveals significant health and well-being challenges in IDPs compared to host communities. Studies confirm this as the prevalence of physical illness, depression, and anxiety disorders is reportedly higher among IDPs compared to non-displaced populations [@Kouadio2012].

### Associations Between Wellbeing Attributes with Perceived Levels of social cohesion and Resilience

The analysis of the wellbeing attributes in relation to social cohesion and resilience reveals distinct patterns of association as shown in @tbl-health-cohesion-resilience. Regarding social cohesion, not all wellbeing attributes showed significant impacts. Health status, physical health status, relationships with family, and worry about global events did not have significant associations. However, relationships with friends (p = 0.002) and optimism about the next 12 months (p = 0.047) were significantly associated with social cohesion, indicating that strong friendships and a positive outlook on the future contribute to a sense of social cohesion. These findings are consistent with existing literature, which highlights the importance of social capital (trust, community ties, and civic engagement) in health outcomes and subjective well-being. Social capital is linked to better physical health and well-being [@helliwell2004; @ngamaba2017; @ross2002]**.** The positive association between social cohesion and well-being is complex and context-dependent, influenced by various dimensions of social capital and resilience [@lanzi2011; @quinn2020; @derrico2017].

In terms of resilience, the associations were more consistently significant. Health status (p \< 0.001), physical health status (p \< 0.001), relationships with family (p = 0.004), relationships with friends (p \< 0.001), worry about global events (p \< 0.001), and optimism about the next 12 months (p \< 0.001) all showed strong positive associations with resilience. This underscores the importance of both physical wellbeing and social connections in fostering resilience, while also suggesting that awareness and concern about global issues may enhance resilience through adaptive coping mechanisms. Overall, while only certain attributes were linked to social cohesion, a comprehensive range of wellbeing factors significantly influenced resilience, highlighting the multifaceted nature of resilience. Research indicates that higher resilience levels are associated with better health outcomes, quality of life, and lower healthcare utilization and expenditures [@vanschrojensteinlantman2017; @wells2009; @musich2022; @färber2018]. Resilience is linked to perceived health, immune functioning, and positive mental health, particularly in older adults and those with chronic illness [@stewart2011; @färber2018].
